site_name: Survey Genie
site_description: JSON-configured survey prototypes using the ONS Design System

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Environment variables: environment-variables.md
  - Survey definitions: survey-definition.md
  - Supported ONS components: ons-components.md

theme:
  name: material
