steps:
  - name: gcr.io/$PROJECT_ID/testrunner
    args:
      - '-c'
      - |
        set -e
        echo === Check Tooling Versions ===
        gcloud --version
        make --version
        pip --version
        python --version
        poetry --version

        echo === Install dependencies for tests ===
        poetry install
        make templates

        echo === Running unit tests ===
        poetry run pytest -q --maxfail=1 --disable-warnings --cov-report term-missing --cov-fail-under=80 | tee coverage-report.txt
        if grep -q "FAIL Required test coverage" coverage-report.txt; then
          echo "ERROR: Target coverage was not reached, stopping pipeline."
          exit 1
        fi

        echo === Looking up config from parameter store ===
        config=$(gcloud parametermanager parameters versions describe $_ENV_NAME --parameter=infra-test-config --location=global --project $PROJECT_ID --format=json | python3 -c "import sys, json; print(json.load(sys.stdin)['payload']['data'])" | base64 --decode)
        GENIE_UI_IMAGE=$(echo $config | python3 -c "import sys, json; print(json.load(sys.stdin)['cr-genie-ui-image'])")
        TARGET_PROJECT_ID=$(echo $config | python3 -c "import sys, json; print(json.load(sys.stdin)['project-id'])")
        export PROXY_API_URL=$(echo $config | python3 -c "import sys, json; print(json.load(sys.stdin)['proxy-api-url'])")

        echo === Build Docker image, tag and push to GAR ===
        docker build -t $$GENIE_UI_IMAGE:$SHORT_SHA -t $$GENIE_UI_IMAGE:latest .
        docker push $$GENIE_UI_IMAGE:latest
        docker push $$GENIE_UI_IMAGE:$SHORT_SHA

        echo === Deploy GENIE UI ===
        gcloud run deploy genie-ui --image=$$GENIE_UI_IMAGE:$SHORT_SHA --region $LOCATION --project $$TARGET_PROJECT_ID

        echo === Run smoke tests ===

        export TARGET_ENVIRONMENT=$_ENV_NAME
        export UI_SA_ID_TOKEN=$(gcloud auth print-identity-token) # Use CICD service account
        export GENIE_UI_URL=$$PROXY_API_URL # set to proxy API
        poetry run pytest -s cicd

    id: Run unit tests, build, tag and deploy Genie cloud run job
    entrypoint: bash
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
